### PR TITLE
Remove unused resetPort.py

### PR DESCRIPTION
**Pull request by eriknyquist**
@bbaltz505 @calvinatintel please review

### CODE REVIEW

**Comment by eriknyquist** [comment]
@calvinatintel this doesn't seem to affect anything, I can't find anything else that is using resetPort.py.

Note that https://github.com/01org/CODK-A-ARC/commit/e2600caff6e5b15409e779ff7267abab07d8ccfd has already been merged. Can you confirm that this copy of resetPort.py isn't being used by anything else?

**Comment by calvinatintel** [comment]
Nothing beats a test cycle. How about pulling it in and running the examples? Or have you done that already? Then I can try the same

**Comment by calvinatintel** [comment]
Tested on Z. Now testing on M.

**Comment by calvinatintel** [comment]
Tested on M.

**Review by calvinatintel — APPROVED** [review]

**Pull request merged**
